DATA TO PULL:
    - Projected and Actual points by week
        a) Projected only available for past and upcoming week (if in season)
        b) Need to pull this at the week/team/player level and aggregate in order to get projected points
        c) HAVE CODE FOR THIS
    - Indicator if week is part of regular season or playoffs
        a) HAVE CODE FOR THIS
    - Team IDs, Names, and Divisions (mapped to team)
    - Number of teams (can do this several different ways)
    
    
TODO:
    - Pull team data (team level)
        a) teamId, divisionId, full name, nickname
    - Pull settings data (league level)
        a) see settingsData cell
    - Pull matchup data (team/week level)
        a) teamId, scoringPeriod, matchupPeriod, score
        b) This will primarily be used to verify the team/week aggregate from the week/team/player data
            1. Note: Concern here is the possibility of non-player scores (e.g. "home team bonus") throwing
            things off
    - Update league finder function to only include leagues that actually have data
        a) Consider looking for more leagues (should only have around 500 or so that can actually be used)
    - Data checks
        a) Get freqs for the different settings variables
            1. This should help provide more clarity regarding what each variable actually is
        b) Compare week/team score of matchup data to agg of week/team/player data
    - Data processing
        a) Agg week/team/player data

In [291]:
import requests
import pandas as pd
import numpy as np

from ratelimit import limits, sleep_and_retry

pd.options.display.max_columns = None
pd.options.display.max_rows = 100

slotcodes = {
    0 : 'QB', 2 : 'RB', 4 : 'WR',
    6 : 'TE', 16: 'Def', 17: 'K',
    20: 'Bench', 21: 'IR', 23: 'Flex'
}


def convert_tuple_to_list(tuple_var):
    """ 
    Converts tuple to a list
    Note: This isn't really necessary, but accounts for 1D tuple cases so i'm using it
    """
    
    list_var = []
    
    # Need to process 1D and 2D tuples differently
    if type(tuple_var[0]) is tuple:
        for value in tuple_var:

            dict_key = value[0]
            dict_value = value[1]

            list_var.append([dict_key, dict_value])
    else:
        dict_key = tuple_var[0]
        dict_value = tuple_var[1]

        list_var.append([dict_key, dict_value])
            
    return list_var


def convert_dict_to_list(dict_var):
    """ Converts dictionary to a 2D list """
    
    list_var = []
    for param, param_value in dict_var.items():
        list_var.append([param, param_value])
        
    return list_var


@sleep_and_retry
@limits(calls=6000, period=600)
def pull_data(seasonId, leagueId, params = []):
    """ Returns a JSON object containing the data pulled APIs url """
    
    if seasonId < 2020:
        url = "https://fantasy.espn.com/apis/v3/games/ffl/leagueHistory/" + \
              str(leagueId) + "?seasonId=" + str(seasonId)
    else:
        url = "https://fantasy.espn.com/apis/v3/games/ffl/seasons/" + \
              str(seasonId) + "/segments/0/leagues/" + str(leagueId)
    
    # Passing the dict_params directly to the request_params of the requests.get method was
    # resulting in certain pulls retrieving unspecified data.
    # So, I'm directly applying those parameters to the URL string to prevent this
    # Note: This was likely happening due to duplicate keys being used (e.g. "view") in the dict
    if type(params) is tuple:
        params = convert_tuple_to_list(params)
        
    if type(params) is dict:
        params = convert_dict_to_list(params)
    
    for full_param in params:
        param = str(full_param[0])
        param_value = str(full_param[1])
        
        if url.find("?") == -1:
            url = url + "?" + param + "=" + param_value
        else:
            url = url + "&" + param + "=" + param_value
    
    r = requests.get(url)
    
    status_code = r.status_code
    
    if r.status_code == 200:
        pass
    else:
        if r.status_code == 429:
            print("429 error")

        return None   
    
    # 2020 url returns JSON object while prior seasonIds return it in a list 
    if seasonId < 2020:
        d = r.json()[0]
    else:
        d = r.json()
        
    r.close()
        
    return d


def create_week_team_player_df(seasonId, leagueId, week_start=1, week_end=17):
    data = []
    for week in range(week_start, week_end + 1):

        request_params = (("view", "mMatchup"), ("view", "mMatchupScore"), ("scoringPeriodId", week))

        d = pull_data(seasonId, leagueId, params=request_params)

        try:            
            for tm in d['teams']:
                tmid = tm['id']
                for p in tm['roster']['entries']:
                    name = p['playerPoolEntry']['player']['fullName']

                    slot = p['lineupSlotId']
                    pos  = slotcodes[slot]

                    # injured status (need try/exc bc of D/ST)
                    inj = 'NA'
                    try:
                        inj = p['playerPoolEntry']['player']['injuryStatus']
                    except:
                        pass

                    # projected/actual points
                    proj, act = None, None
                    for stat in p['playerPoolEntry']['player']['stats']:
                        if stat['scoringPeriodId'] != week:
                            continue
                        if stat['statSourceId'] == 0:
                            act = stat['appliedTotal']
                        elif stat['statSourceId'] == 1:
                            proj = stat['appliedTotal']

                    data.append([week, tmid, name, slot, pos, inj, proj, act])
                    
        except:
            pass
                
    columns = ['Week', 'Team', 'Player', 'Slot', 'Pos', 'Status', 'Proj', 'Actual']
                
    data = pd.DataFrame(data, columns=columns)
                
    return data

# 28056918
matchup_data = create_week_team_player_df(2020, 48347143, week_end=1)
# settings_data = pull_data(2019, 28056918, params=(("view", "mSettings")))

matchup_data.loc[matchup_data['Team']==1]

,Week,Team,Player,Slot,Pos,Status,Proj,Actual
0,1,1,Alvin Kamara,2,RB,OUT,17.406407,21.20
1,1,1,Travis Kelce,6,TE,ACTIVE,14.886366,14.00
2,1,1,Chris Carson,2,RB,ACTIVE,14.635647,21.60
3,1,1,Calvin Ridley,4,WR,ACTIVE,11.783908,32.40
4,1,1,Keenan Allen,23,Flex,OUT,11.671297,5.70
5,1,1,Will Fuller V,4,WR,SUSPENSION,11.766370,18.20
6,1,1,J.K. Dobbins,20,Bench,ACTIVE,7.680690,14.20
7,1,1,Henry Ruggs III,20,Bench,ACTIVE,8.207652,8.10
8,1,1,CeeDee Lamb,20,Bench,ACTIVE,8.513200,8.40
9,1,1,Drew Brees,0,QB,ACTIVE,18.545038,14.40
10,1,1,Darrel Williams,20,Bench,ACTIVE,6.816641,4.00
11,1,1,Parris Campbell,20,Bench,INJURY_RESERVE,7.030014,11.00
12,1,1,Damien Harris,21,IR,OUT,0.000000,0.00
13,1,1,Jalen Reagor,20,Bench,ACTIVE,6.185375,6.00
14,1,1,Ryquell Armstead,21,IR,OUT,0.000000,0.00
15,1,1,James Robinson,20,Bench,OUT,8.471582,9.50
16,1,1,Titans D/ST,16,Def,NA,7.015284,3.00
17,1,1,Malcolm Brown,20,Bench,ACTIVE,5.495873,24.50
18,1,1,Ryan Fitzpatrick,20,Bench,OUT,16.202511,5.44

In [138]:
"""
Additional data to pull:
    - playoffSeedingRule
    - playoffSeedigRuleBy
    - num_playoff_teams
    - firstScoringPeriod
    - finalScoringPeriod
    - scoring_type
    - reg_season_matchup_tiebreaker
    - playoff_matchup_tiebreaker
    - home_team_bonus

"""

class settingsData():
    """ Pulls the relevant league settings """
    
    def __init__(self, raw_settings_data):
        
        schedule_settings = raw_settings_data['settings']['scheduleSettings']
        scoring_settings = raw_settings_data['settings']['scoringSettings']
        status_settings = raw_settings_data['settings']['status']
        
        self.league_name = raw_settings_data['settings']['name']
        
        self.num_divisions = len(schedule_settings['divisions'])
        self.df_divisions = self._pull_divisions(raw_settings_data)
        
        self.num_playoff_teams = schedule_settings['playoffTeamCount']
        self.playoff_seeding_tiebreaker = schedule_settings['playoffSeedingRule']
        
        # Not sure what this is at the moment. Usually is just 0
        self.playoffSeedingRuleBy = schedule_settings['playoffSeedingRuleBy']
        self.playoffSeedingRule = schedule_settings['playoffSeedingRule']
        self.num_reg_season_matchups = schedule_settings['matchupPeriodCount']
        
        self.reg_season_matchup_tiebreaker = scoring_settings['matchupTieRule']
        self.playoff_matchup_tiebreaker = scoring_settings['playoffMatchupTieRule']
        
        self.home_team_bonus = scoring_settings['homeTeamBonus']
        
        # Not sure what this is yet - returns "H2H_POINTS"
        self.scoring_type = scoring_settings['scoringType']
        
        
        self.firstScoringPeriod = status_settings['firstScoringPeriod']
        self.finalScoringPeriod = status_settings['finalScoringPeriod']
        

        
        #NEED THIS
        self.df_scoring_periods = self._pull_scoring_period_lookup(raw_settings_data, 
                                                                   self.num_reg_season_matchups)
    
    def _pull_divisions(self, raw_settings_data):
        """ Return dataframe containing the name and size of each division """
        
        divisions_list = raw_settings_data['settings']['scheduleSettings']['divisions']

        divisions = []
        for division in divisions_list:
            division_name = division['name']
            division_size = division['size']
            divisionId = division['id']

            divisions.append([division_name, division_size, divisionId])
            
        columns = ['division_name', 'division_size', 'divisionId']
        divisions = pd.DataFrame(divisions, columns=columns)

        return divisions
        
    def _pull_scoring_period_lookup(self, raw_settings_data, num_reg_season_matchups):
        """ Returns dataframe containing the scoring period mapped to matchup period """
        
        reg_season_matchups_pds = raw_settings_data['settings']['scheduleSettings']['matchupPeriods']
        
        scoring_pd_list = []
        for matchup_pd, scoring_pds in reg_season_matchups_pds.items():
            
            matchup_pd = int(matchup_pd)   
            for scoring_pd in scoring_pds:
                
                scoring_pd = int(scoring_pd)

                scoring_pd_list.append([scoring_pd, matchup_pd])
                
        columns = ['scoringPeriodId', 'macthupPeriodId']
        df = pd.DataFrame(scoring_pd_list, columns=columns)
        
        week_type_conditions = [
            (df['macthupPeriodId'] <= num_reg_season_matchups),
            (df['macthupPeriodId'] > num_reg_season_matchups)
        ]

        df['regular_season_ind'] = np.select(week_type_conditions, [1, 0])
                
        return df

# check_settings = settingsData(settings_data)
# print(check_settings.df_divisions)
# check_settings.df_scoring_periods

  division_name  division_size  divisionId
0          East              3           0
1          West              3           1

    scoringPeriodId  macthupPeriodId  regular_season_ind
0                 1                1                   1
1                 2                2                   1
2                 3                3                   1
3                 4                4                   1
4                 5                5                   1
5                 6                6                   1
6                 7                7                   1
7                 8                8                   1
8                 9                9                   1
9                10               10                   1
10               11               11                   1
11               12               12                   1
12               13               13                   1
13               14               14                   0
14               15               14                   0
15               16               15                   0
16               17               15                   0

In [326]:
class teamData():
    """ Pulls relevant team data """
    
    def __init__(self, raw_mTeam_data):
             
        self.df_members_names = self._pull_team_members_names(raw_mTeam_data)
        self.df_divisions = self._pull_team_division(raw_mTeam_data)
        
        self.df_team_data = self._merge_division_id(raw_mTeam_data)
        
    def _pull_team_members_names(self, raw_mTeam_data):
        """ Creates a dataframe containing each team members full name """
        
        members_data = raw_mTeam_data['members']
        
        team_data = []
        for team in members_data:
            
            try:
                team_firstName = team['firstName']
                team_lastName = team['lastName']
                team_fullName = team_firstName + " " + team_lastName
            except:
                team_firstName = np.nan
                team_lastName = np.nan
                team_fullName = np.nan
            
            # id" in this portion of the API data returns the "primaryOwnerKey" from the "teams" section
            team_primaryOwnerKey = team['id']
            
            team_data.append([team_fullName, team_primaryOwnerKey])
            
        columns = ['team_fullName', 'team_primaryOwnerKey']
        df = pd.DataFrame(team_data, columns=columns)
        
        return df
    
    def _pull_team_division(self, raw_mTeam_data):
        """ Returns dataframe contaiing each teams division Id"""
        teams_data = raw_mTeam_data['teams']
        
        team_data = []
        for team in teams_data:
            
            team_divisionId = team['divisionId']
            team_id = team['id']
            
            # Not sure why, but this isn't always included for a team
            try:
                team_primaryOwnerKey = team['primaryOwner']
            except:
                team_primaryOwnerKey = "N/A"
            
            team_data.append([team_divisionId, team_id, team_primaryOwnerKey])
            
        columns = ['team_divisionId', 'team_id', 'team_primaryOwnerKey']
        df = pd.DataFrame(team_data, columns=columns)
        
        return df
    
    def _merge_division_id(self, raw_mTeam_data):
        """ Returns dataframe with team member names and division Id merged together """
        
        df_team_members_names = self._pull_team_members_names(raw_mTeam_data)
        df_team_divisions = self._pull_team_division(raw_mTeam_data)
        
        df = pd.merge(df_team_members_names, df_team_divisions, on='team_primaryOwnerKey')
        
        return df
        
    

# check_team_data = teamData(team_data)
# check_team_data.df_team_data

In [302]:

def create_league_df(seasonId, leagueId, week_start=1, week_end=17):
    """ 
    Returns a dataframe containing the initial data necessary for the simulation
    for one league/year
    
    Note: the settings_data and team_data objects are a bit overkill for this, but I'm using them
    in case there's any additional data that needs to be pulled in the future
    """
    
    df_week_team_player = create_week_team_player_df(seasonId, leagueId, 
                                                     week_start=week_start, week_end=week_end)
    
    if len(df_week_team_player) == 0:
        return None
    
    else:
        settings_data = pull_data(seasonId, leagueId, params=(("view", "mSettings")))
        settings_data = settingsData(settings_data)

        team_data = pull_data(seasonId, leagueId, params=(('view', 'mTeam')))
        team_data = teamData(team_data)

        df_divisions = settings_data.df_divisions[['divisionId', 'division_name']]
        df_team_data = team_data.df_team_data
        df_team_data = pd.merge(df_team_data, df_divisions,
                            left_on='team_divisionId', right_on='divisionId', how='left')

        df_scoring_periods = settings_data.df_scoring_periods
        df_week_team_player = pd.merge(df_week_team_player, df_scoring_periods,
                                      left_on='Week', right_on='scoringPeriodId', how='left')

        df_league_data = pd.merge(df_week_team_player, df_team_data,
                                left_on='Team', right_on='team_id', how='left')

        df_league_data.drop(['team_id', 'scoringPeriodId', 
                             'team_primaryOwnerKey', 'divisionId'], 1, inplace=True)
        df_league_data.rename(columns={'division_name': 'team_division_name'}, inplace=True)

    return df_league_data
    

check = create_league_df(2020, 48347143, week_end=1)
check

,Week,Team,Player,Slot,Pos,Status,Proj,Actual,macthupPeriodId,regular_season_ind,team_fullName,team_divisionId,team_division_name
0,1,1,Alvin Kamara,2,RB,OUT,17.406407,21.20,1,1,Connor DeLong,0,East
1,1,1,Travis Kelce,6,TE,ACTIVE,14.886366,14.00,1,1,Connor DeLong,0,East
2,1,1,Chris Carson,2,RB,ACTIVE,14.635647,21.60,1,1,Connor DeLong,0,East
3,1,1,Calvin Ridley,4,WR,ACTIVE,11.783908,32.40,1,1,Connor DeLong,0,East
4,1,1,Keenan Allen,23,Flex,OUT,11.671297,5.70,1,1,Connor DeLong,0,East
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1,12,Austin Hooper,20,Bench,ACTIVE,6.595182,2.50,1,1,Matt Fleisher,0,East
201,1,12,Nyheim Hines,20,Bench,ACTIVE,7.610436,23.30,1,1,Matt Fleisher,0,East
202,1,12,Colts D/ST,16,Def,NA,8.107672,4.00,1,1,Matt Fleisher,0,East
203,1,12,Derek Carr,20,Bench,ACTIVE,18.112839,13.56,1,1,Matt Fleisher,0,East
204,1,12,Danny Amendola,20,Bench,ACTIVE,8.191634,10.60,1,1,Matt Fleisher,0,East

In [341]:
# file_dir = 'check.csv'
# check.to_csv(file_dir, mode='a', header=True, index=False)

def get_league_ids(leagues_found_csv='Leagues_Found.csv'):

    df_leagues_found = pd.read_csv(leagues_found_csv)

    df_leagues_found = df_leagues_found.loc[df_leagues_found['seasonId'] == 2020]
    
    league_ids = list(df_leagues_found['leagueId'])
    
    return league_ids



def pull_all_leagues(season_id, league_ids, index_start, index_end):
    
    num_leagues = len(league_ids)
    
    if index_end > num_leagues:
        print("All Leagues have been processed")
        index_end = num_leagues    
    
    # This creates an empty dataframe that will be used for stacking
    get_cols_for_empty_df = create_league_df(2020, 48347143, week_end=1)
    
    columns = list(get_cols_for_empty_df.columns)
    columns.append('league_found_index')
    columns.append('league_id')
    
    df_league_data = pd.DataFrame(columns=columns)
    
    for i in range(index_start, index_end):
        league_id = league_ids[i]
        
        print(league_id, ": ", i)

        df_append_league_data = create_league_df(2020, league_id, week_end=17)
        
        if df_append_league_data is None:
            pass
        else:
            df_append_league_data['league_found_index'] = i

            df_append_league_data['league_id'] = league_id

            df_league_data = df_league_data.append(df_append_league_data)
    
    return df_league_data
        

league_ids = get_league_ids()
all_leagues = pull_all_leagues(2020, league_ids, 3000, 4000)


# df_league_data = create_league_df(2020, 48347719)
# print(list(df_league_data.columns))

# df_league_data
# 42731353
all_leagues

All Leagues have been processed
58613026 :  3000
58613159 :  3001
58613347 :  3002
58613467 :  3003
58613539 :  3004
58613643 :  3005
58613644 :  3006
58613741 :  3007
58614096 :  3008
58614181 :  3009
58614365 :  3010
58614563 :  3011
58614644 :  3012
58614791 :  3013
58614849 :  3014
58614903 :  3015
58615215 :  3016
58615500 :  3017
58615622 :  3018
58615673 :  3019
58616246 :  3020
58616433 :  3021
58616628 :  3022
58616716 :  3023
58617035 :  3024
58617208 :  3025
58617353 :  3026
58617597 :  3027
58617677 :  3028
58617738 :  3029
58617821 :  3030
58617989 :  3031
58618082 :  3032
58618138 :  3033
58618287 :  3034
58618655 :  3035
58618834 :  3036
58619293 :  3037
58619314 :  3038
58619327 :  3039
58619484 :  3040
58619793 :  3041
58620253 :  3042
58620319 :  3043
58620455 :  3044
58620817 :  3045
58621378 :  3046
58621465 :  3047
58621594 :  3048
58621828 :  3049
58621878 :  3050
58621906 :  3051
58622128 :  3052
58622490 :  3053
58622747 :  3054
58623016 :  3055
58623040 :  3056
58623806 :  3057
58623834 :  3058
58623903 :  3059
58623917 :  3060
58623999 :  3061
58624237 :  3062
58624732 :  3063
58625074 :  3064
58625144 :  3065
58625335 :  3066
58625357 :  3067
58625376 :  3068
58625453 :  3069
58625551 :  3070
58625649 :  3071
58625847 :  3072
58625899 :  3073
58626032 :  3074
58626047 :  3075
58626252 :  3076
58626253 :  3077
58626396 :  3078
58626461 :  3079
58626733 :  3080
58626811 :  3081
58627302 :  3082
58627316 :  3083
58628234 :  3084
58628292 :  3085
58629002 :  3086
58629104 :  3087
58629338 :  3088
58629411 :  3089
58629552 :  3090
58629856 :  3091
58629867 :  3092
58630214 :  3093
58630329 :  3094
58630489 :  3095
58630520 :  3096
58631009 :  3097
58631061 :  3098
58631146 :  3099
58631229 :  3100
58631242 :  3101
58631637 :  3102
58631878 :  3103
58632326 :  3104
58632351 :  3105
58632503 :  3106
58632583 :  3107
58632714 :  3108
58632834 :  3109
58632861 :  3110
58633021 :  3111
58633059 :  3112
58633109 :  3113
58633753 :  3114
58634064 :  3115
58634271 :  3116
58634534 :  3117
58635101 :  3118
58635352 :  3119
58635421 :  3120
58635656 :  3121
58635800 :  3122
58636052 :  3123
58636233 :  3124
58636387 :  3125
58636943 :  3126
58637093 :  3127
58637678 :  3128
58637847 :  3129
58637990 :  3130
58638185 :  3131
58638404 :  3132
58638673 :  3133
58638779 :  3134
58639088 :  3135
58639265 :  3136
58639824 :  3137
58639857 :  3138
58640157 :  3139
58640181 :  3140
58640381 :  3141
58640612 :  3142
58640751 :  3143
58641173 :  3144
58641332 :  3145
58641820 :  3146
58641874 :  3147
58642042 :  3148
58642064 :  3149
58642409 :  3150
58642473 :  3151
58642647 :  3152
58642977 :  3153
58643209 :  3154
58643477 :  3155
58644359 :  3156
58644425 :  3157
58644686 :  3158
58645119 :  3159
58645770 :  3160
58645835 :  3161
58646442 :  3162
58646567 :  3163
58646855 :  3164
58646879 :  3165
58647042 :  3166
61547414 :  3167
61547756 :  3168
61547831 :  3169
61548519 :  3170
61548776 :  3171
61548942 :  3172
61549094 :  3173
61549877 :  3174
61549949 :  3175
61550017 :  3176
61550171 :  3177
61551266 :  3178
61551302 :  3179
61551446 :  3180
61551514 :  3181
61551642 :  3182
61551747 :  3183
61551995 :  3184
61551998 :  3185
61552618 :  3186
61552685 :  3187
61553027 :  3188
61553158 :  3189
61553361 :  3190
61553622 :  3191
61553879 :  3192
61554108 :  3193
61554240 :  3194
61554388 :  3195
61554403 :  3196
61554835 :  3197
61554851 :  3198
61555378 :  3199
61555649 :  3200
61555713 :  3201
61556093 :  3202
61556214 :  3203
61556420 :  3204
61556491 :  3205
61556785 :  3206
61557714 :  3207
61557715 :  3208
61557973 :  3209
61558538 :  3210
61558690 :  3211
61558697 :  3212
61559042 :  3213
61559234 :  3214
61559585 :  3215
61559746 :  3216
61559886 :  3217
61559896 :  3218
61560266 :  3219
61560736 :  3220
61561073 :  3221
61561186 :  3222
61561243 :  3223
61561479 :  3224
61562524 :  3225
61562633 :  3226
61562773 :  3227
61562886 :  3228
61563623 :  3229
61563688 :  3230
61563973 :  3231
61564001 :  3232
61564104 :  3233
61564177 :  3234
61564267 :  3235
61564391 :  3236
61564752 :  3237
61564911 :  3238
61565544 :  3239
61565617 :  3240
61565756 :  3241
61565795 :  3242
61565851 :  3243
61566282 :  3244
61566294 :  3245
61566458 :  3246
61566735 :  3247
61566810 :  3248
61567123 :  3249
61567134 :  3250
61567277 :  3251
61567841 :  3252
61568103 :  3253
61568140 :  3254
61568340 :  3255
61568422 :  3256
61568589 :  3257
61568602 :  3258
61569214 :  3259
61569508 :  3260
61569788 :  3261
61570355 :  3262
61572282 :  3263
61572511 :  3264
61572553 :  3265
61572803 :  3266
61572936 :  3267
61573065 :  3268
61573339 :  3269
61573414 :  3270
61573477 :  3271
61573523 :  3272
61573539 :  3273
61574194 :  3274
61574404 :  3275
61574710 :  3276
61574921 :  3277
61576187 :  3278
61576277 :  3279
61576341 :  3280
61576737 :  3281
61576977 :  3282
61577332 :  3283
61577446 :  3284
61577493 :  3285
61577747 :  3286
61578050 :  3287
61578100 :  3288
61578146 :  3289
61578297 :  3290
61578436 :  3291
61578730 :  3292
61579142 :  3293
61579926 :  3294
61580153 :  3295
61580321 :  3296
61580481 :  3297
61580601 :  3298
61580963 :  3299
61581061 :  3300
61581354 :  3301
61581366 :  3302
61581487 :  3303
61581755 :  3304
61581903 :  3305
61582078 :  3306
61582652 :  3307
61582810 :  3308
61582850 :  3309
61582991 :  3310
61582999 :  3311
61583261 :  3312
61583343 :  3313
61583658 :  3314
61583744 :  3315
61584943 :  3316
61585074 :  3317
61585287 :  3318
61585374 :  3319
61585593 :  3320
61585662 :  3321
61585663 :  3322
61586324 :  3323
61586358 :  3324
61586611 :  3325
61587148 :  3326
61587161 :  3327
61587171 :  3328
61587531 :  3329
61587763 :  3330
61587771 :  3331
61587781 :  3332
61588007 :  3333
61588012 :  3334
61588232 :  3335
61588387 :  3336
61588389 :  3337
61588393 :  3338
61588491 :  3339
61588668 :  3340
61588780 :  3341
61588800 :  3342
61588994 :  3343
61589096 :  3344
61589114 :  3345
61589187 :  3346
61589444 :  3347
61589652 :  3348
61589708 :  3349
61589771 :  3350
61590137 :  3351
61590427 :  3352
61590574 :  3353
61590828 :  3354
61590916 :  3355
61590998 :  3356
61591267 :  3357
61591546 :  3358
61591606 :  3359
61591868 :  3360
61592118 :  3361
61592260 :  3362
61592309 :  3363
61592511 :  3364
61592543 :  3365
61592562 :  3366
61592727 :  3367
61592981 :  3368
61593047 :  3369
61593074 :  3370
61593287 :  3371
61593438 :  3372
61593512 :  3373
61593663 :  3374
61593877 :  3375
61593988 :  3376
61594253 :  3377
61594293 :  3378
61594646 :  3379
61594803 :  3380
61595002 :  3381
61595065 :  3382
61595293 :  3383
61595602 :  3384
61595831 :  3385
61595840 :  3386
61595896 :  3387
61596285 :  3388
61596332 :  3389
61596710 :  3390
61596907 :  3391
61597182 :  3392
61597794 :  3393
61598037 :  3394
61598067 :  3395
61598069 :  3396
61598077 :  3397
61598674 :  3398
61598984 :  3399
61599579 :  3400
61599932 :  3401
61600090 :  3402
61600417 :  3403
61600470 :  3404
61600497 :  3405
61600738 :  3406
61600810 :  3407
61600829 :  3408
61601165 :  3409
61601391 :  3410
61601558 :  3411
61601644 :  3412
61601684 :  3413
61601734 :  3414
61601973 :  3415
61602335 :  3416
61602416 :  3417
61602546 :  3418
61603014 :  3419
61603174 :  3420
61603606 :  3421
61603938 :  3422
61604647 :  3423
61605680 :  3424
61605846 :  3425
61606271 :  3426
61606377 :  3427
61606412 :  3428
61606672 :  3429
61606733 :  3430
61606795 :  3431
61607061 :  3432
61607135 :  3433
61607346 :  3434
61607620 :  3435
61607735 :  3436
61607787 :  3437
61608115 :  3438
61608552 :  3439
61608625 :  3440
61608634 :  3441
61608980 :  3442
61608998 :  3443
61609079 :  3444
61609409 :  3445
61609456 :  3446
61609506 :  3447
61609668 :  3448
61609700 :  3449
61609717 :  3450
61610183 :  3451
61610259 :  3452
61610368 :  3453
61610452 :  3454
61610724 :  3455
61611279 :  3456
61611344 :  3457
61611575 :  3458
61611655 :  3459
61611988 :  3460
61612015 :  3461
61612311 :  3462
61612931 :  3463
61613422 :  3464
61613524 :  3465
61613704 :  3466
61613899 :  3467
61614049 :  3468
61614120 :  3469
61614173 :  3470
61614374 :  3471
61614702 :  3472
61615056 :  3473
61615062 :  3474
61615148 :  3475
61615987 :  3476
61616093 :  3477
61616161 :  3478
61617024 :  3479
61617183 :  3480

61617207 :  3481
61617327 :  3482
61617693 :  3483
61617753 :  3484
61618330 :  3485
61619198 :  3486
61619250 :  3487
61619468 :  3488
61620024 :  3489
61620127 :  3490
61620357 :  3491
61620508 :  3492
61620516 :  3493
61620637 :  3494
61620818 :  3495
61621145 :  3496
61621230 :  3497
61621263 :  3498
61621353 :  3499
61621590 :  3500
61622130 :  3501
61622527 :  3502
61622912 :  3503
61623243 :  3504
61623354 :  3505
61623658 :  3506
61624167 :  3507
61624170 :  3508
61625287 :  3509
61625433 :  3510
61625450 :  3511
61625523 :  3512
61625529 :  3513
61625747 :  3514
61625828 :  3515
61626173 :  3516
61626244 :  3517
61626789 :  3518
61626927 :  3519
61626948 :  3520
61627227 :  3521
61627667 :  3522
61627757 :  3523
61627782 :  3524
61627900 :  3525
61628091 :  3526
61628302 :  3527
61628389 :  3528
61628955 :  3529
61629011 :  3530
61629248 :  3531
61629656 :  3532
61630042 :  3533
61630050 :  3534
61630265 :  3535
61630478 :  3536
61630593 :  3537
61630751 :  3538
61630916 :  3539
61631485 :  3540
61631615 :  3541
61632101 :  3542
61632199 :  3543
61632504 :  3544
61632573 :  3545
61632679 :  3546
61632770 :  3547
61632952 :  3548
61633008 :  3549
61633111 :  3550
61633310 :  3551
61633734 :  3552
61633962 :  3553
61633995 :  3554
61634001 :  3555
61634145 :  3556
61635057 :  3557
61635235 :  3558
61635443 :  3559
61635491 :  3560
61635814 :  3561
61635940 :  3562
61636158 :  3563
61636167 :  3564
61636222 :  3565
61636531 :  3566
61636651 :  3567
61636864 :  3568
61636870 :  3569
61637032 :  3570
61637049 :  3571
61637181 :  3572
61637251 :  3573
61637830 :  3574
61638059 :  3575
61638275 :  3576
61638969 :  3577
61639416 :  3578
61639898 :  3579
61640066 :  3580
61640098 :  3581
61640143 :  3582
61640440 :  3583
61640833 :  3584
61641432 :  3585
61641679 :  3586
61641738 :  3587
61641950 :  3588
61642270 :  3589
61642293 :  3590
61642394 :  3591
61642472 :  3592
61642652 :  3593
61642695 :  3594
61642796 :  3595
61642879 :  3596
61643494 :  3597
61643562 :  3598
61643607 :  3599
61643692 :  3600
61643696 :  3601
61643762 :  3602
61644401 :  3603
61644444 :  3604
61644576 :  3605
61644613 :  3606
61645133 :  3607
61645581 :  3608
61646059 :  3609
61646104 :  3610
61646239 :  3611
61646548 :  3612
61646864 :  3613
61647118 :  3614
61647238 :  3615
61647429 :  3616

,Week,Team,Player,Slot,Pos,Status,Proj,Actual,macthupPeriodId,regular_season_ind,team_fullName,team_divisionId,team_division_name,league_found_index,league_id
0,1,1,Miles Sanders,20,Bench,OUT,0.000000,0.0,1,1,Tony Suek,0,East,3000,58613026
1,1,1,Nick Chubb,2,RB,ACTIVE,14.633902,5.6,1,1,Tony Suek,0,East,3000,58613026
2,1,1,A.J. Brown,4,WR,ACTIVE,13.662708,8.9,1,1,Tony Suek,0,East,3000,58613026
3,1,1,Tyler Lockett,4,WR,ACTIVE,14.632152,17.2,1,1,Tony Suek,0,East,3000,58613026
4,1,1,David Montgomery,23,Flex,ACTIVE,10.176080,8.4,1,1,Tony Suek,0,East,3000,58613026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2729,17,10,Chase Claypool,4,WR,ACTIVE,10.377665,21.1,15,0,Quinn McIlvanie,1,West,3616,61647429
2730,17,10,Noah Fant,20,Bench,ACTIVE,11.205609,8.8,15,0,Quinn McIlvanie,1,West,3616,61647429
2731,17,10,Giovani Bernard,20,Bench,ACTIVE,11.558791,0.7,15,0,Quinn McIlvanie,1,West,3616,61647429
2732,17,10,Kalen Ballage,20,Bench,ACTIVE,7.053212,9.6,15,0,Quinn McIlvanie,1,West,3616,61647429
2733,17,10,Cole Kmet,6,TE,ACTIVE,7.444513,9.1,15,0,Quinn McIlvanie,1,West,3616,61647429

In [343]:
# NEED TO DEDUP THIS NOW
file_dir = 'All_Leagues_Data.csv'
all_leagues.to_csv(file_dir, mode='a', header=False, index=False)

In [319]:
import sys

sys.path

['/home/cdelong/Python-Projects/FF-Web-App/Repo-Work/delt-ff-dashboard/simulation_work',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '',
 '/home/cdelong/Python-Projects/FF-Web-App/venv/lib/python3.8/site-packages',
 '/home/cdelong/Python-Projects/FF-Web-App/venv/lib/python3.8/site-packages/IPython/extensions',
 '/home/cdelong/.ipython']

In [344]:
all_leagues_processed = pd.read_csv('All_Leagues_Data.csv')

# leagues_found = pd.read_csv('Leagues_Found.csv')

leagues_processed_list = all_leagues_processed.groupby(['league_id'], as_index=False).size()

print(len(leagues_processed_list))
print(len(all_leagues))
print(len(all_leagues_processed))

2170
1248359
5603054

/******************************************************************************************************/
/******************************************************************************************************/
/***************************************** SCRATCH WORK ***********************************************/
/******************************************************************************************************/
/******************************************************************************************************/

In [223]:
# 28056918
# 48347143
# settings_data = pull_settings_data(2020, league_id=28056918)[0]

# Need to loop through scoring periods, but can do all teams with one pull

request_params = (("forTeamId", 1), ("view", "mRoster")
#                   , ("scoringPeriodId", 10)
#                  ,("view", "overview")
#                   ,("view", "singleScoringPeriod")
                 )

request_params = (("view", "mMatchup"), ("view", "mMatchupScore"), ("scoringPeriodId", 10))

roster_data = pull_data(2020, 48347143, params=request_params)

print(roster_data.keys(), "\n")

print(roster_data['scoringPeriodId'])

# print(roster_data['teams'][0].keys(), "\n")

# print(roster_data['teams'][0]['roster']['entries'][0].keys(), "\n")

# print(roster_data['teams'][0]['roster']['entries'][0]['lineupSlotId'])

# playerPool = roster_data['teams'][0]['roster']['entries'][0]['playerPoolEntry']

# print("CHECK THIS: ", playerPool.keys(), "\n")

# print(playerPool['player'].keys(), "\n")

# print(playerPool['player']['rankings'].keys(), "\n")

# print(playerPool['player']['rankings']['0'], "\n")

dict_keys(['draftDetail', 'gameId', 'id', 'schedule', 'scoringPeriodId', 'seasonId', 'segmentId', 'status', 'teams'])

10

In [129]:
def pull_week_team_player_data_new(seasonId, leagueId):

    data = []
    for week_number in range(1, 5):
        
        request_params = (("forTeamId", 1), ("view", "mRoster"), ("scoringPeriodId", week_number),
                         ("view", "overview"), ("statSplit", "singleScoringPeriod"))

        roster_data = pull_data(seasonId, league_id=leagueId, dict_params=request_params)[0]
        
        for player in roster_data['teams'][0]['roster']['entries']:
            
            slot = player['lineupSlotId']
            position  = slotcodes[slot]
            
            playerPool = player['playerPoolEntry']
            
            week_number_str = str(week_number)
            
            try:
                alt_slot = playerPool['player']['rankings'][week_number_str][0]['slotId']
                alt_position = slotcodes[alt_slot]
            except:
                alt_position = "N/A"
            
            player_name = player['playerPoolEntry']['player']['fullName']
            
            data.append([player_name, position, alt_position, week_number])
            
    columns = ['player_name', 'position', 'alt_position', 'week_number']
    
    df = pd.DataFrame(data, columns=columns)
    
    return df
            
check = pull_week_team_player_data_new(2019, 48347143)

check
    
# print(len(roster_data['teams'][0]['roster']['entries']))

            player_name position alt_position  week_number
0   Christian McCaffrey       RB           RB            1
1     Leonard Fournette       RB           RB            1
2            Mike Evans       IR           WR            1
3         Tyler Lockett       WR           WR            1
4         Derrius Guice       IR           RB            1
5       Damien Williams    Bench           RB            1
6       Ronald Jones II    Bench           RB            1
7        Jameis Winston       QB           QB            1
8            49ers D/ST    Bench          Def            1
9          Kenyan Drake     Flex           RB            1
10           A.J. Brown    Bench          N/A            1
11          O.J. Howard       TE           TE            1
12      Jacoby Brissett    Bench           QB            1
13         Broncos D/ST      Def          Def            1
14            Jets D/ST    Bench          Def            1
15     Breshad Perriman       WR          N/A            1
16       Ameer Abdullah    Bench          N/A            1
17  Christian McCaffrey       RB          N/A            2
18    Leonard Fournette       RB           RB            2
19           Mike Evans       IR          N/A            2
20        Tyler Lockett       WR           WR            2
21        Derrius Guice       IR          N/A            2
22      Damien Williams    Bench           RB            2
23      Ronald Jones II    Bench          N/A            2
24       Jameis Winston       QB           QB            2
25           49ers D/ST    Bench          Def            2
26         Kenyan Drake     Flex           RB            2
27           A.J. Brown    Bench          N/A            2
28          O.J. Howard       TE          N/A            2
29      Jacoby Brissett    Bench           QB            2
30         Broncos D/ST      Def          Def            2
31            Jets D/ST    Bench          Def            2
32     Breshad Perriman       WR          N/A            2
33       Ameer Abdullah    Bench          N/A            2
34  Christian McCaffrey       RB           RB            3
35    Leonard Fournette       RB           RB            3
36           Mike Evans       IR           WR            3
37        Tyler Lockett       WR           WR            3
38        Derrius Guice       IR          N/A            3
39      Damien Williams    Bench          N/A            3
40      Ronald Jones II    Bench           RB            3
41       Jameis Winston       QB           QB            3
42           49ers D/ST    Bench          Def            3
43         Kenyan Drake     Flex           RB            3
44           A.J. Brown    Bench          N/A            3
45          O.J. Howard       TE           TE            3
46      Jacoby Brissett    Bench           QB            3
47         Broncos D/ST      Def          Def            3
48            Jets D/ST    Bench          N/A            3
49     Breshad Perriman       WR          N/A            3
50       Ameer Abdullah    Bench          N/A            3
51  Christian McCaffrey       RB           RB            4
52    Leonard Fournette       RB           RB            4
53           Mike Evans       IR           WR            4
54        Tyler Lockett       WR           WR            4
55        Derrius Guice       IR          N/A            4
56      Damien Williams    Bench           RB            4
57      Ronald Jones II    Bench           RB            4
58       Jameis Winston       QB           QB            4
59           49ers D/ST    Bench          N/A            4
60         Kenyan Drake     Flex           RB            4
61           A.J. Brown    Bench          N/A            4
62          O.J. Howard       TE           TE            4
63      Jacoby Brissett    Bench           QB            4
64         Broncos D/ST      Def          Def            4
65            Jets D/ST    Bench          N/A            4
66     Breshad Perriman       WR          N/A            4
67       Ameer Abdullah    Bench          N/A            4

In [42]:

@sleep_and_retry
@limits(calls=6000, period=600)
def pull_data_old(year, league_id = 0, dict_params = {}):
    """ Returns a JSON object containing the data pulled APIs url """
    if league_id == 0:
        url = "https://fantasy.espn.com/apis/v3/games/ffl/seasons/" + str(year)
    else:
        if year < 2020:
            url = "https://fantasy.espn.com/apis/v3/games/ffl/leagueHistory/" + \
                  str(league_id) + "?seasonId=" + str(year)
        else:
            url = "https://fantasy.espn.com/apis/v3/games/ffl/seasons/" + \
                  str(year) + "/segments/0/leagues/" + str(league_id)     
        
    r = requests.get(url, params=dict_params)
    
    status_code = r.status_code
    
    if r.status_code == 200:
        pass
    else:
        if r.status_code == 429:
            print("429 error")

        return None   
    
    # 2020 url returns JSON object while prior years return it in a list 
    if year < 2020:
        d = r.json()[0]
    else:
        d = r.json()
        
    r.close()
        
    return [d, status_code

200
404

In [68]:
file = '/home/cdelong/python_projects/ff_web_app/delt_ff_standings/Leagues_Found.csv'

leagues_found = pd.read_csv(file)

leagueIds = list(leagues_found['leagueId'])

status_codes = []
for league in leagueIds[0:100]:
    status_code = pull_data(2019, league_id=league)[1]
    
    status_codes.append([league, status_code])

d_status_codes = pd.DataFrame(status_codes, columns=['leagueId', 'status_codes'])

d_status_codes

    leagueId  status_codes
0   48347143           200
1   48347191           200
2   48347259           200
3   48347360           200
4   48347430           200
..       ...           ...
95  28056904           200
96  28056918           200
97  28056993           200
98  28057018           200
99  28057031           200

[100 rows x 2 columns]